### ISSUE TITLE
Exporter directory missing?

### ISSUE THREAD

**Issue by kneoyskw** [gameprogcpp/code#13]
On page 193 of the book "Game Programming in C++" , 2nd line, it says "To solve this, the GitHub code repository provides two exporters in the **Exporter** directory" but I can not find it.

**Comment by BMarques** [comment]
I'm having the same issue ... The exporter directory is important to understand the whole flow, specially as in page 195, it says "As a performance improvement, you could instead compute this radius in the gpmesh exporter.".

**Comment by chalonverse** [comment]
Oops. For some reason GitHub set this repo as "not watched" so I didn't see this until now.

I've pushed the Blender export script to the Exporter directory. It's simpler than the Unreal exporter because it does not handle skeletal models/animations.

I plan on posting the Unreal exporter soon, but first I need to verify that it still functions with the current version of Unreal (or if not, I'll have to add that stipulation).

**Comment by tannic1973** [comment]
I'm having some troubles running the script from blened.
When i try to export, i get the following errors:
Traceback (most recent call last):
  File "C:\Users\ra\Documents\monkey.blend\gpmesh_export.py", line 100, in execute
  File "C:\Users\ra\Documents\monkey.blend\gpmesh_export.py", line 34, in write_gpmesh
AttributeError: 'NoneType' object has no attribute 'data'
location: <unknown location>:-1
what should i do to get it working ?

**Comment by chalonverse** [comment]
@tannic1973 I think you need to make sure a mesh object is selected in the scene view before exporting it?

**Comment by KazuyaOrimoto** [comment]
Please tell me the correct procedure, even if you put the exporter in Blender add-on file, even if Add-on installation Blender does not recognize it.

**Comment by chalonverse** [comment]
@KazuyaOrimoto I made a short video showing how to use the plugin: https://www.youtube.com/watch?v=ukLQH_-IsLs

**Comment by BitmapTarachan** [comment]
I am very saved thanks to your book.
Could you give us a .gpanim and .gpskel file exporter to get a deeper understanding of the animation in chapter 12?
Thank you.

**Comment by tannic1973** [comment]
Hi,

I do as you show in the video, but i get the following output:
Traceback (most recent call last):
  File "\Text", line 100, in execute
  File "\Text", line 34, in write_gpmesh
AttributeError: 'NoneType' object has no attribute 'data'

location: <unknown location>:-1

just using the standard cube.

Regards
tannic1973


Den ons. 3. jul. 2019 kl. 03.23 skrev chalonverse <notifications@github.com

**Comment by sugimonSmash** [comment]
please give us how-to gpanim and gpskel exporter. I'm sad. please.......sorry...little English...

**Comment by chalonverse** [comment]
@tannic1973 If you get that error that means you have the mesh selected, instead of the object that cintains the mesh

@BitmapTarachan @sugimonSmash The problem is that Unreal has rewritten their method for how they store skeletal meshes. My current plugin doesn't work after these changes. I'lll try to update the exporter so it works with the 4.22.x (which is the current version)

**Comment by sugimonSmash** [comment]
@chalonverse  thank you XD. If there is a script that can output bone animation data created by Blender as "gpanim, gpskel", please publish it. This is the same as outputting gpmesh in Blender + Script. Could you? I want to use the animation I made. I am not selfish. English is difficult. I'm sorry. :( . I respect you. :D

**Comment by tannic1973** [comment]
Hi,
i still get the same error message. Running Blender 2.79

An export from a simple cube results in the following file:
{
"version":1,
"vertexformat":"PosNormTex",
"shader":"BasicMesh",
"textures":[
"untitled.png"
],
"specularPower":100,



Den lør. 27. jul. 2019 kl. 00.50 skrev chalonverse <notifications@github.com

**Comment by chalonverse** [comment]
@sugimonSmash I've just added the Unreal Engine exporter plugin, so you can now export skeletal meshes, skeletons, and animation files from Unreal into the formats used by the book. I don't know enough about how Blender stores its animation to write an exporter for animations directly from Blender. However, you could export from Blender into an FBX, then import the FBX into Unreal, and finally you could export to the book's formats using this new plugin.

@tannic1973 I'm not sure exactly, but I believe the script also may not work if there's no texture assigned to the object, because there wouldn't be an texture coordinates to export.

**Comment by tannic1973** [comment]
Got it working, by adding a texture. thanks!

Den tor. 1. aug. 2019 kl. 03.57 skrev chalonverse <notifications@github.com

**Comment by sugimonSmash** [comment]
@chalonverse  Thank you very very very much much :DDDDD.  I'd like to thank you from the bottom of my heart. XD.  Now I can complete the 3D action game!

**Comment by kainigh** [comment]
Hello 

I tried to use the Blender add to export a mesh but every time I try I get an output but it does not look the same as the video and it does not work with the code. 
![meshoutput](https://github.com/gameprogcpp/code/assets/147383316/8bf3aff3-57d0-4022-8921-75d56814a087)

**Comment by kainigh** [comment]
I also tried using Unreal to export a .gpmesh file but after I follow the instructions and rebuild, I get an error say "Project could not be complied. Try rebuilding for source manually. "
